server:
  port: 9200

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: work-service
          uri: lb://work-service
          predicates:
            - Path=/work-service/**
          filters:
            - StripPrefix=1
        - id: work-admin
          uri: lb://work-admin
          predicates:
            - Path=/work-admin/**
          filters:
            - StripPrefix=1
        - id: life-service
          uri: lb://life-service
          predicates:
            - Path=/life-service/**
          filters:
            - StripPrefix=1
        - id: life-admin
          uri: lb://life-admin
          predicates:
            - Path=/life-admin/**
          filters:
            - StripPrefix=1
        - id: home-service
          uri: lb://home-service
          predicates:
            - Path=/home-service/**
          filters:
            - StripPrefix=1
        - id: home-admin
          uri: lb://home-admin
          predicates:
            - Path=/home-admin/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/