server:
  port: 9001

spring:
  application:
    name: work-service
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/work?useSSL=false&characterEncoding=utf8
    username: mk_work
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql
    # 初始化脚本
    #schema: classpath:schema-work.sql
    #data: classpath:data-work.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.work.model

management:
  endpoints:
    web:
      exposure:
        include: health,info  # 暴露健康检查端点
  endpoint:
    health:
      show-details: always    # 显示详细信息